// @ts-nocheck
import { AssetsPageSection } from '@/modules/assets-page-section'
import { BacktestPageSection, BuilderPageSection } from '@/modules/builder-backtest-sections'
import { LivePageSection, PaperPageSection } from '@/modules/live-paper-sections'
import { SystemPageSection } from '@/modules/system-page-section'
import {
  ASSET_MIN_MONTH,
  BACKTEST_MAX_MONTH,
  BACKTEST_MIN_MONTH,
  envFieldGroups,
  HABIT_OPTIONS,
  HISTORY_MAX_MONTH,
  PAIRS,
} from '@/modules/constants'
import { normalizeDecimal, normalizeLeverage } from '@/modules/trade-utils'
import { fmtNum, fmtPct, fmtTime } from '@/modules/format'

export function DashboardContent({ c, renderOverviewCards }) {
  return (
    <>
      {c.menu === 'live' && (
        <LivePageSection
          activePair={c.activePair}
          setActivePair={c.setActivePair}
          pairs={PAIRS}
          strategyPickerRef={c.strategyPickerRef}
          strategyPickerOpen={c.strategyPickerOpen}
          setStrategyPickerOpen={c.setStrategyPickerOpen}
          enabledStrategies={c.enabledStrategies}
          setStrategyDraft={c.setStrategyDraft}
          selectedStrategyText={c.selectedStrategyText}
          executionStrategyOptions={c.executionStrategyOptions}
          strategyDraft={c.strategyDraft}
          toggleStrategyDraft={c.toggleStrategyDraft}
          confirmStrategySelection={c.confirmStrategySelection}
          settings={c.settings}
          setSettings={c.setSettings}
          normalizeDecimal={normalizeDecimal}
          normalizeLeverage={normalizeLeverage}
          refreshCore={c.refreshCore}
          runningNow={c.runningNow}
          runOneCycle={c.runOneCycle}
          toggleScheduler={c.toggleScheduler}
          schedulerRunning={c.schedulerRunning}
          savingSettings={c.savingSettings}
          saveLiveConfig={c.saveLiveConfig}
          liveViewTab={c.liveViewTab}
          setLiveViewTab={c.setLiveViewTab}
          renderOverviewCards={renderOverviewCards}
          liveStrategyLabel={c.liveStrategyLabel}
          tradeRecords={c.tradeRecords}
        />
      )}

      {c.menu === 'paper' && (
        <PaperPageSection
          paperPair={c.paperPair}
          setPaperPair={c.setPaperPair}
          pairs={PAIRS}
          paperStrategyPickerRef={c.paperStrategyPickerRef}
          paperStrategyPickerOpen={c.paperStrategyPickerOpen}
          setPaperStrategyPickerOpen={c.setPaperStrategyPickerOpen}
          paperStrategySelection={c.paperStrategySelection}
          setPaperStrategyDraft={c.setPaperStrategyDraft}
          paperSelectedStrategyText={c.paperSelectedStrategyText}
          executionStrategyOptions={c.executionStrategyOptions}
          paperStrategyDraft={c.paperStrategyDraft}
          togglePaperStrategyDraft={c.togglePaperStrategyDraft}
          confirmPaperStrategySelection={c.confirmPaperStrategySelection}
          paperMargin={c.paperMargin}
          setPaperMargin={c.setPaperMargin}
          paperSettings={c.paperSettings}
          setPaperSettings={c.setPaperSettings}
          normalizeDecimal={normalizeDecimal}
          normalizeLeverage={normalizeLeverage}
          startPaperSim={c.startPaperSim}
          paperSimLoading={c.paperSimLoading}
          paperSimRunning={c.paperSimRunning}
          pausePaperSim={c.pausePaperSim}
          paperViewTab={c.paperViewTab}
          setPaperViewTab={c.setPaperViewTab}
          renderOverviewCards={renderOverviewCards}
          paperTradeRecords={c.paperTradeRecords}
        />
      )}

      {c.menu === 'assets' && (
        <AssetsPageSection
          assetOverview={c.assetOverview}
          assetDistribution={c.assetDistribution}
          assetMonth={c.assetMonth}
          setAssetMonth={c.setAssetMonth}
          assetCalendar={c.assetCalendar}
          assetRange={c.assetRange}
          setAssetRange={c.setAssetRange}
          assetTrend={c.assetTrend}
          minMonth={ASSET_MIN_MONTH}
          maxMonth={HISTORY_MAX_MONTH}
        />
      )}

      {c.menu === 'builder' && (
        <BuilderPageSection
          builderTab={c.builderTab}
          setBuilderTab={c.setBuilderTab}
          strategyGenMode={c.strategyGenMode}
          habit={c.habit}
          setHabit={c.setHabit}
          habitOptions={HABIT_OPTIONS}
          genPair={c.genPair}
          setGenPair={c.setGenPair}
          pairs={PAIRS}
          genStyle={c.genStyle}
          setGenStyle={c.setGenStyle}
          genMinRR={c.genMinRR}
          setGenMinRR={c.setGenMinRR}
          genLowConfAction={c.genLowConfAction}
          setGenLowConfAction={c.setGenLowConfAction}
          genDirectionBias={c.genDirectionBias}
          setGenDirectionBias={c.setGenDirectionBias}
          genAllowReversal={c.genAllowReversal}
          setGenAllowReversal={c.setGenAllowReversal}
          generateStrategy={c.generateStrategy}
          generatingStrategy={c.generatingStrategy}
          setUploadFile={c.setUploadFile}
          loadStrategyTemplate={c.loadStrategyTemplate}
          loadingTemplate={c.loadingTemplate}
          copyStrategyTemplate={c.copyStrategyTemplate}
          uploadStrategy={c.uploadStrategy}
          uploadingStrategy={c.uploadingStrategy}
          strategyTemplate={c.strategyTemplate}
          generatedStrategies={c.generatedStrategies}
          selectedRuleId={c.selectedRuleId}
          setSelectedRuleId={c.setSelectedRuleId}
          selectedRule={c.selectedRule}
          renameRuleName={c.renameRuleName}
          setRenameRuleName={c.setRenameRuleName}
          renameGeneratedStrategy={c.renameGeneratedStrategy}
          deleteGeneratedStrategy={c.deleteGeneratedStrategy}
          renameHanCount={c.renameHanCount}
          fmtNum={fmtNum}
        />
      )}

      {c.menu === 'backtest' && (
        <BacktestPageSection
          btStrategyPickerRef={c.btStrategyPickerRef}
          btStrategyPickerOpen={c.btStrategyPickerOpen}
          setBtStrategyPickerOpen={c.setBtStrategyPickerOpen}
          btStrategySelection={c.btStrategySelection}
          setBtStrategyDraft={c.setBtStrategyDraft}
          btSelectedStrategyText={c.btSelectedStrategyText}
          executionStrategyOptions={c.executionStrategyOptions}
          btStrategyDraft={c.btStrategyDraft}
          toggleBtStrategyDraft={c.toggleBtStrategyDraft}
          confirmBtStrategySelection={c.confirmBtStrategySelection}
          btPair={c.btPair}
          setBtPair={c.setBtPair}
          pairs={PAIRS}
          btInitialMargin={c.btInitialMargin}
          setBtInitialMargin={c.setBtInitialMargin}
          btLeverage={c.btLeverage}
          setBtLeverage={c.setBtLeverage}
          normalizeLeverage={normalizeLeverage}
          btPositionSizingMode={c.btPositionSizingMode}
          setBtPositionSizingMode={c.setBtPositionSizingMode}
          btHighConfidenceAmount={c.btHighConfidenceAmount}
          setBtHighConfidenceAmount={c.setBtHighConfidenceAmount}
          btLowConfidenceAmount={c.btLowConfidenceAmount}
          setBtLowConfidenceAmount={c.setBtLowConfidenceAmount}
          btHighConfidenceMarginPct={c.btHighConfidenceMarginPct}
          setBtHighConfidenceMarginPct={c.setBtHighConfidenceMarginPct}
          btLowConfidenceMarginPct={c.btLowConfidenceMarginPct}
          setBtLowConfidenceMarginPct={c.setBtLowConfidenceMarginPct}
          normalizeDecimal={normalizeDecimal}
          btStart={c.btStart}
          setBtStart={c.setBtStart}
          btEnd={c.btEnd}
          setBtEnd={c.setBtEnd}
          backtestMinMonth={BACKTEST_MIN_MONTH}
          backtestMaxMonth={BACKTEST_MAX_MONTH}
          runBacktest={c.runBacktest}
          btRunning={c.btRunning}
          btHistoryLoading={c.btHistoryLoading}
          btHistory={c.btHistory}
          btHistorySelectedId={c.btHistorySelectedId}
          viewBacktestHistoryDetail={c.viewBacktestHistoryDetail}
          fmtNum={fmtNum}
          fmtTime={fmtTime}
          selectedBacktestHistory={c.selectedBacktestHistory}
          fmtPct={fmtPct}
          btSummary={c.btSummary}
          btHistoryDeletingId={c.btHistoryDeletingId}
          removeBacktestHistory={c.removeBacktestHistory}
          btRecords={c.btRecords}
        />
      )}

      {c.menu === 'system' && (
        <SystemPageSection
          systemSubTab={c.systemSubTab}
          setSystemSubTab={c.setSystemSubTab}
          loadingSystemRuntime={c.loadingSystemRuntime}
          loadSystemRuntime={c.loadSystemRuntime}
          restartingBackend={c.restartingBackend}
          restartBackend={c.restartBackend}
          runtimeComponents={c.runtimeComponents}
          systemRuntime={c.systemRuntime}
          fmtNum={fmtNum}
          fmtTime={fmtTime}
          envFieldGroups={envFieldGroups}
          systemSettings={c.systemSettings}
          setSystemSettings={c.setSystemSettings}
          systemSaveHint={c.systemSaveHint}
          savingSystemSettings={c.savingSystemSettings}
          saveSystemEnv={c.saveSystemEnv}
          setEditingLLMId={c.setEditingLLMId}
          resetLLMModalDraft={c.resetLLMModalDraft}
          setNewLLM={c.setNewLLM}
          setShowLLMModal={c.setShowLLMModal}
          llmProductCatalog={c.llmProductCatalog}
          llmConfigs={c.llmConfigs}
          testingLLMId={c.testingLLMId}
          llmStatusMap={c.llmStatusMap}
          testLLMConfigReachability={c.testLLMConfigReachability}
          openEditLLMModal={c.openEditLLMModal}
          deletingLLMId={c.deletingLLMId}
          removeLLMConfig={c.removeLLMConfig}
          setShowExchangeModal={c.setShowExchangeModal}
          exchangeBound={c.exchangeBound}
          activeExchangeId={c.activeExchangeId}
          exchangeConfigs={c.exchangeConfigs}
          activatingExchangeId={c.activatingExchangeId}
          bindExchangeAccount={c.bindExchangeAccount}
          deletingExchangeId={c.deletingExchangeId}
          removeExchangeAccount={c.removeExchangeAccount}
          promptSettings={c.promptSettings}
          setPromptSettings={c.setPromptSettings}
          resetPromptConfig={c.resetPromptConfig}
          resettingPrompts={c.resettingPrompts}
          savePromptConfig={c.savePromptConfig}
          savingPrompts={c.savingPrompts}
        />
      )}
    </>
  )
}
