package server

import (
	"fmt"
	"strings"
)

func normalizeStrategySymbolForName(symbol string) string {
	v := strings.ToUpper(strings.TrimSpace(symbol))
	if v == "" {
		return "通用"
	}
	base := v
	if strings.Contains(base, "-") {
		parts := strings.Split(base, "-")
		if len(parts) > 0 {
			base = parts[0]
		}
	} else if strings.HasSuffix(base, "USDT") && len(base) > 4 {
		base = strings.TrimSuffix(base, "USDT")
	}
	switch base {
	case "BTC":
		return "比特币"
	case "ETH":
		return "以太坊"
	case "BNB":
		return "币安币"
	case "SOL":
		return "索拉纳"
	case "XRP":
		return "瑞波币"
	case "DOGE":
		return "狗狗币"
	case "ADA":
		return "艾达币"
	default:
		return base
	}
}

func normalizeStrategyHabitForName(habit string) string {
	v := strings.TrimSpace(strings.ToLower(habit))
	switch v {
	case "10m":
		return "10分钟"
	case "1h":
		return "1小时"
	case "4h":
		return "4小时"
	case "1d":
		return "1日"
	case "5d":
		return "5日"
	case "30d":
		return "30日"
	case "90d":
		return "90日"
	default:
		if v == "" {
			return "标准周期"
		}
		return strings.ToUpper(v)
	}
}

func normalizeStrategyStyleForName(style string) string {
	v := strings.TrimSpace(strings.ToLower(style))
	switch v {
	case "trend_follow", "trend_following", "trend":
		return "趋势"
	case "breakout":
		return "突破"
	case "mean_reversion":
		return "均值回归"
	case "hybrid":
		return "混合"
	default:
		if v == "" {
			return "综合"
		}
		return "自定义"
	}
}

func buildStandardStrategyName(symbol, habit, style string, autoGenerated bool) string {
	symbolLabel := normalizeStrategySymbolForName(symbol)
	habitLabel := normalizeStrategyHabitForName(habit)
	styleLabel := normalizeStrategyStyleForName(style)
	name := fmt.Sprintf("%s-%s-%s策略", symbolLabel, habitLabel, styleLabel)
	if autoGenerated {
		return "自动重生成-" + name
	}
	return name
}

func normalizeStrategySymbolForKey(symbol string) string {
	v := strings.ToUpper(strings.TrimSpace(symbol))
	if v == "" {
		return "GENERIC"
	}
	if strings.Contains(v, "-") {
		parts := strings.Split(v, "-")
		if len(parts) > 0 && strings.TrimSpace(parts[0]) != "" {
			return strings.TrimSpace(parts[0]) + "USDT"
		}
	}
	return v
}

func normalizeStyleForKey(style string) string {
	v := strings.TrimSpace(strings.ToLower(style))
	switch v {
	case "trend_follow", "trend_following", "trend":
		return "trend_following"
	case "breakout":
		return "breakout"
	case "mean_reversion":
		return "mean_reversion"
	default:
		return "hybrid"
	}
}

func buildStrategyRuleKey(symbol, habit, style string, autoGenerated bool) string {
	scope := "manual"
	if autoGenerated {
		scope = "auto"
	}
	return strings.ToLower(fmt.Sprintf(
		"%s|%s|%s|%s",
		scope,
		normalizeStrategySymbolForKey(symbol),
		normalizeHabitInput(habit),
		normalizeStyleForKey(style),
	))
}
